In [36]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [37]:
#pip install matplotlib --force-reinstall


In [38]:
# load data
file = 'pumpkin/Pumpkin_Seeds_Dataset/Pumpkin_Seeds_Dataset.xlsx'
df = pd.read_excel(file, sheet_name='Pumpkin_Seeds_Dataset',engine='openpyxl')

In [39]:
df.shape

(2500, 13)

In [40]:
df.head()

Area  Perimeter  Major_Axis_Length  Minor_Axis_Length  Convex_Area  \
0  56276    888.242           326.1485           220.2388        56831   
1  76631   1068.146           417.1932           234.2289        77280   
2  71623   1082.987           435.8328           211.0457        72663   
3  66458    992.051           381.5638           222.5322        67118   
4  66107    998.146           383.8883           220.4545        67117   

   Equiv_Diameter  Eccentricity  Solidity  Extent  Roundness  Aspect_Ration  \
0        267.6805        0.7376    0.9902  0.7453     0.8963         1.4809   
1        312.3614        0.8275    0.9916  0.7151     0.8440         1.7811   
2        301.9822        0.8749    0.9857  0.7400     0.7674         2.0651   
3        290.8899        0.8123    0.9902  0.7396     0.8486         1.7146   
4        290.1207        0.8187    0.9850  0.6752     0.8338         1.7413   

   Compactness       Class  
0       0.8207  Çerçevelik  
1       0.7487  Çerçevelik  
2       0.6929  Çerçevelik  
3       0.7624  Çerçevelik  
4       0.7557  Çerçevelik

In [41]:
df['Class'].unique()
df['Class'] = df['Class'].map({'Çerçevelik': 0, 'Ürgüp Sivrisi': 1})
df.head()


Area  Perimeter  Major_Axis_Length  Minor_Axis_Length  Convex_Area  \
0  56276    888.242           326.1485           220.2388        56831   
1  76631   1068.146           417.1932           234.2289        77280   
2  71623   1082.987           435.8328           211.0457        72663   
3  66458    992.051           381.5638           222.5322        67118   
4  66107    998.146           383.8883           220.4545        67117   

   Equiv_Diameter  Eccentricity  Solidity  Extent  Roundness  Aspect_Ration  \
0        267.6805        0.7376    0.9902  0.7453     0.8963         1.4809   
1        312.3614        0.8275    0.9916  0.7151     0.8440         1.7811   
2        301.9822        0.8749    0.9857  0.7400     0.7674         2.0651   
3        290.8899        0.8123    0.9902  0.7396     0.8486         1.7146   
4        290.1207        0.8187    0.9850  0.6752     0.8338         1.7413   

   Compactness  Class  
0       0.8207      0  
1       0.7487      0  
2       0.6929      0  
3       0.7624      0  
4       0.7557      0

In [42]:
X = df.drop('Class',axis=1)
y=df['Class']

In [43]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20)

In [44]:
from sklearn.svm import SVC
svcclassifier = SVC(kernel='linear')
svcclassifier.fit(X_train,y_train)

SVC(kernel='linear')

In [45]:
y_pred=svcclassifier.predict(X_test)

In [46]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[231  24]
 [ 36 209]]
              precision    recall  f1-score   support

           0       0.87      0.91      0.89       255
           1       0.90      0.85      0.87       245

    accuracy                           0.88       500
   macro avg       0.88      0.88      0.88       500
weighted avg       0.88      0.88      0.88       500



## Kernel SVM

In [47]:
from sklearn.model_selection import train_test_split
X_train1, X_test1, y_train1, y_test1 = train_test_split(X, y, test_size = 0.20)

In [48]:
from sklearn.svm import SVC
#Polynomial
svcclassifier1 = SVC(kernel='poly',degree=8)
svcclassifier1.fit(X_train, y_train)

SVC(degree=8, kernel='poly')

In [49]:
y_pred1 = svcclassifier1.predict(X_test)


In [50]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred1))
print(classification_report(y_test,y_pred1))

[[232  23]
 [191  54]]
              precision    recall  f1-score   support

           0       0.55      0.91      0.68       255
           1       0.70      0.22      0.34       245

    accuracy                           0.57       500
   macro avg       0.62      0.57      0.51       500
weighted avg       0.62      0.57      0.51       500



In [51]:
from sklearn.svm import SVC
#Gaussian
svclassifier2 = SVC(kernel='rbf')
svclassifier2.fit(X_train, y_train)

SVC()

In [52]:
y_pred2 = svclassifier2.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred2))
print(classification_report(y_test, y_pred2))

[[221  34]
 [184  61]]
              precision    recall  f1-score   support

           0       0.55      0.87      0.67       255
           1       0.64      0.25      0.36       245

    accuracy                           0.56       500
   macro avg       0.59      0.56      0.51       500
weighted avg       0.59      0.56      0.52       500



In [53]:
#sigmoid
from sklearn.svm import SVC
svclassifier2 = SVC(kernel='sigmoid')
svclassifier2.fit(X_train, y_train)

SVC(kernel='sigmoid')

In [35]:
y_pred2 = svclassifier2.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred2))
print(classification_report(y_test, y_pred2))

[[119 131]
 [152  98]]
              precision    recall  f1-score   support

           0       0.44      0.48      0.46       250
           1       0.43      0.39      0.41       250

    accuracy                           0.43       500
   macro avg       0.43      0.43      0.43       500
weighted avg       0.43      0.43      0.43       500

